- name: "Update/upgrade packages"
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: "Install nodejs."
  become: yes
  apt:
    update_cache: yes
    name: ["nodejs", "npm"]
    state: latest

- name: "Install PM2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
