- name: create the application folder
  become: yes
  ansible.builtin.file:
    path: /opt/udapeople/backend
    state: directory
    mode: '0755'

- name: copy backend dist archive
  become: yes
  copy:
    src: /home/circleci/project/backend/dist.tar.gz
    dest: /opt/udapeople/backend/dist.tar.gz

- name: extract dist.tar.gz
  become: yes
  unarchive:
    src: /opt/udapeople/backend/dist.tar.gz
    dest: /opt/udapeople/backend
    remote_src: yes

- name: debug ls
  command: ls -l /opt/udapeople/backend
  register: ls_out

- debug: var=ls_out.stdout_lines

- name: start PM2 service
  become: yes
  command: pm2 start -f ./main.js
  args:
    chdir: /opt/udapeople/backend
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
